aliases:
  - &pull-submodules
    name: Pull Submodules
    command: |
      ssh-keyscan gitlab.rlp.net >> ~/.ssh/known_hosts
      git submodule init
      git submodule update
  - &install-dependencies
    name: Install dependencies
    command: |
      apk add --update --no-cache nodejs nodejs-npm python make g++ pkgconfig libsecret-dev
      npm config set unsafe-perm true
      npm i -g npm
      node --version
      npm --version
      npm i -g @quasar/cli
      npm install

version: 2
jobs:
  release_dev:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: *pull-submodules
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Dev Image
          command: |
            set +o pipefail
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            npm run lint
            npm run docker-release-dev

  release_production:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: *pull-submodules
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          command: |
            set +o pipefail
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t motionbank/systems-frontend:${CIRCLE_BRANCH} .
            docker push motionbank/systems-frontend:${CIRCLE_BRANCH}

  release_legacy:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: *pull-submodules
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          command: |
            set +o pipefail
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t motionbank/systems-frontend:${CIRCLE_BRANCH} .
            docker push motionbank/systems-frontend:${CIRCLE_BRANCH}

workflows:
  version: 2
  build_pipeline:
    jobs:
      - release_dev:
          filters:
            branches:
              only: master
      - release_production:
          filters:
            branches:
              only: /^release_2_.+$/
      - release_legacy:
          filters:
            branches:
              only: /^release_1_.+$/
